// GENERATED — do not edit by hand. Run: node tools/gen-spell-data.mjs
//
// Spell/ability reference for the Spell Monitor's badges and abbreviations,
// derived from Lich's `scripts/data/base-spells.yaml` (430 entries).
// Committed rather than read from a Lich install, because the Spell Monitor
// works without Lich (Principle #2) — see tools/gen-spell-data.mjs.
//
// Keys are the effect names EXACTLY as DR writes them in the percWindow stream;
// that they match the YAML keys verbatim (apostrophes, roman numerals) is the
// fact this whole feature rests on, verified against a real capture.
//
// KNOWN COVERAGE GAP: Thief Khri are absent from base-spells.yaml entirely, yet
// they DO appear in percWindow — so a Thief gets no badges. A missing entry is
// silent by design (no badge), never a wrong one.

/** b = badge letter, l = tooltip label, a = abbreviation, g = guild. Terse keys
 *  because this table is ~29KB in the bundle. */
export interface SpellRef { b: string; l: string; a?: string; g?: string }

export const SPELL_DATA: Record<string, SpellRef> = {
  "Abandoned Heart": {"b":"T","l":"Targeted Magic","a":"ABAN","g":"Bard"},
  "Absolution": {"b":"U","l":"Utility","a":"Absolution","g":"Empath"},
  "Acid Splash": {"b":"T","l":"Targeted Magic","a":"ACS","g":"Necromancer"},
  "Adaptive Curing": {"b":"X","l":"Metamagic","a":"ADC","g":"Empath"},
  "Aegis of Granite": {"b":"A","l":"Augmentation","a":"AEG","g":"Warrior Mage"},
  "Aesandry Darlaeth": {"b":"A","l":"Augmentation","a":"AD","g":"Empath"},
  "Aesrela Everild": {"b":"T","l":"Targeted Magic","a":"AE","g":"Cleric"},
  "Aether Cloak": {"b":"W","l":"Warding","a":"AC","g":"Warrior Mage"},
  "Aether Spheres": {"b":"C","l":"Cantrip","a":"C AE S","g":"Warrior Mage"},
  "Aether Wolves": {"b":"D","l":"Debilitation","a":"AEWO","g":"Bard"},
  "Aethereal Image": {"b":"C","l":"Cantrip","a":"C AE I","g":"Warrior Mage"},
  "Aethrolysis": {"b":"T","l":"Targeted Magic","a":"Aethrolysis","g":"Warrior Mage"},
  "Aggressive Stance": {"b":"A","l":"Augmentation","a":"AGS","g":"Empath"},
  "Air Blast": {"b":"C","l":"Cantrip","a":"C AI B","g":"Warrior Mage"},
  "Air Bubble": {"b":"U","l":"Utility","a":"AB","g":"Warrior Mage"},
  "Air Lash": {"b":"T","l":"Targeted Magic","a":"ALA","g":"Warrior Mage"},
  "Alamhif's Gift": {"b":"U","l":"Utility","a":"AG","g":"Paladin"},
  "Albreda's Balm": {"b":"D","l":"Debilitation","a":"ALB","g":"Bard"},
  "Alkahest Edge": {"b":"X","l":"Metamagic","a":"ALK","g":"Necromancer"},
  "Anger the Earth": {"b":"R","l":"Roar","g":"Barbarian"},
  "Anther's Call": {"b":"D","l":"Debilitation","a":"ANC","g":"Warrior Mage"},
  "Anti-Stun": {"b":"U","l":"Utility","a":"AS","g":"Paladin"},
  "Arbiter's Stylus": {"b":"T","l":"Targeted Magic","a":"ARS","g":"Trader"},
  "Arc Light": {"b":"D","l":"Debilitation","a":"AL","g":"Warrior Mage"},
  "Artificer's Eye": {"b":"A","l":"Augmentation","a":"ART","g":"Moon Mage"},
  "Aspects of the All-God": {"b":"A","l":"Augmentation","a":"ALL","g":"Cleric"},
  "Aspirant's Aegis": {"b":"W","l":"Warding","a":"AA","g":"Paladin"},
  "Athleticism": {"b":"A","l":"Augmentation","a":"ATHLETICISM","g":"Ranger"},
  "Aura of Tongues": {"b":"U","l":"Utility","a":"AOT","g":"Bard"},
  "Aura Sight": {"b":"A","l":"Augmentation","a":"AUS","g":"Moon Mage"},
  "Auspice": {"b":"A","l":"Augmentation","a":"Auspice","g":"Cleric"},
  "Avalanche": {"b":"B","l":"Berserk","g":"Barbarian"},
  "Avren Aevareae": {"b":"D","l":"Debilitation","a":"AVA","g":"Trader"},
  "Avtalia Array": {"b":"X","l":"Metamagic","a":"AVTA","g":"Trader"},
  "Awaken": {"b":"U","l":"Utility","a":"AWAKEN","g":"Empath"},
  "Awaken Forest": {"b":"U","l":"Utility","a":"AF","g":"Ranger"},
  "Axis": {"b":"M","l":"Meditation","g":"Barbarian"},
  "Badger": {"b":"F","l":"Form","g":"Barbarian"},
  "Banner of Truce": {"b":"U","l":"Utility","a":"BOT","g":"Paladin"},
  "Bastion": {"b":"M","l":"Meditation","g":"Barbarian"},
  "Bear": {"b":"F","l":"Form","g":"Barbarian"},
  "Bear Strength": {"b":"A","l":"Augmentation","a":"BES","g":"Ranger"},
  "Beckon the Naga": {"b":"T","l":"Targeted Magic","a":"BTN","g":"Bard"},
  "Benediction": {"b":"A","l":"Augmentation","a":"Benediction","g":"Cleric"},
  "Bespoke Regalia": {"b":"X","l":"Metamagic","g":"Trader"},
  "Bitter Feast": {"b":"X","l":"Metamagic","a":"BF","g":"Cleric"},
  "Blend": {"b":"U","l":"Utility","a":"Blend","g":"Ranger"},
  "Bless": {"b":"U","l":"Utility","a":"bless","g":"Cleric"},
  "Blessing of the Fae": {"b":"A","l":"Augmentation","a":"BOTF","g":"Bard"},
  "Blizzard": {"b":"B","l":"Berserk","g":"Barbarian"},
  "Blood Burst": {"b":"T","l":"Targeted Magic","a":"BLB","g":"Necromancer"},
  "Blood Staunching": {"b":"U","l":"Utility","a":"BS","g":"Empath"},
  "Bloodthorns": {"b":"W","l":"Warding","a":"blood","g":"Ranger"},
  "Blufmor Garaen": {"b":"T","l":"Targeted Magic","a":"BG","g":"Warrior Mage"},
  "Blur": {"b":"A","l":"Augmentation","a":"blur","g":"Trader"},
  "Bond Armaments": {"b":"U","l":"Utility","a":"BA","g":"Paladin"},
  "Bonegrinder": {"b":"T","l":"Targeted Magic","a":"bonegrinder","g":"Necromancer"},
  "Book Burning": {"b":"U","l":"Utility","a":"BB","g":"Necromancer"},
  "Braun's Conjecture": {"b":"U","l":"Utility","a":"BC","g":"Moon Mage"},
  "Breath of Storms": {"b":"T","l":"Targeted Magic","a":"BOS","g":"Bard"},
  "Buffalo": {"b":"F","l":"Form","g":"Barbarian"},
  "Burden": {"b":"D","l":"Debilitation","a":"BURDEN"},
  "Burn": {"b":"T","l":"Targeted Magic","a":"burn","g":"Moon Mage"},
  "Burning Touch": {"b":"C","l":"Cantrip","a":"C B T","g":"Warrior Mage"},
  "Butcher's Eye": {"b":"A","l":"Augmentation","a":"BUE","g":"Necromancer"},
  "Cage of Light": {"b":"W","l":"Warding","a":"CoL","g":"Moon Mage"},
  "Calcified Hide": {"b":"W","l":"Warding","a":"CH","g":"Necromancer"},
  "Calculated Rage": {"b":"T","l":"Targeted Magic","a":"CR","g":"Empath"},
  "Call from Beyond": {"b":"U","l":"Utility","a":"CFB","g":"Necromancer"},
  "Call from Within": {"b":"U","l":"Utility","a":"CFW","g":"Necromancer"},
  "Calm": {"b":"D","l":"Debilitation","a":"calm","g":"Moon Mage"},
  "Caress of the Sun": {"b":"U","l":"Utility","a":"CARE","g":"Bard"},
  "Carrion Call": {"b":"T","l":"Targeted Magic","a":"CAC","g":"Ranger"},
  "Centering": {"b":"A","l":"Augmentation","a":"centering","g":"Cleric"},
  "Chain Lightning": {"b":"T","l":"Targeted Magic","a":"CL","g":"Warrior Mage"},
  "Cheetah Swiftness": {"b":"A","l":"Augmentation","a":"CS","g":"Ranger"},
  "Chill Spirit": {"b":"T","l":"Targeted Magic","a":"CHS","g":"Cleric"},
  "Chirurgia": {"b":"X","l":"Metamagic","a":"CHIR","g":"Necromancer"},
  "Circle of Sympathy": {"b":"U","l":"Utility","a":"COS","g":"Empath"},
  "Clarity": {"b":"A","l":"Augmentation","a":"clarity","g":"Paladin"},
  "Claws of the Cougar": {"b":"A","l":"Augmentation","a":"COTC","g":"Ranger"},
  "Clear Vision": {"b":"A","l":"Augmentation","a":"CV","g":"Moon Mage"},
  "Compel": {"b":"D","l":"Debilitation","a":"COMPEL","g":"Empath"},
  "Compost": {"b":"U","l":"Utility","a":"COMPOST","g":"Ranger"},
  "Concussive": {"b":"S","l":"Scream","g":"Bard"},
  "Consume Flesh": {"b":"U","l":"Utility","a":"CF","g":"Necromancer"},
  "Contemplation": {"b":"M","l":"Meditation","g":"Barbarian"},
  "Contingency": {"b":"U","l":"Utility","a":"CONTINGENCY","g":"Moon Mage"},
  "Courage": {"b":"W","l":"Warding","a":"CO","g":"Paladin"},
  "Covetous Rebirth": {"b":"X","l":"Metamagic","a":"CRE","g":"Necromancer"},
  "Crusader's Challenge": {"b":"A","l":"Augmentation","a":"CRC","g":"Paladin"},
  "Crystal Dart": {"b":"T","l":"Targeted Magic","a":"CRD","g":"Trader"},
  "Crystalize Ice": {"b":"C","l":"Cantrip","a":"C Crystalize Ice","g":"Warrior Mage"},
  "Cure Disease": {"b":"U","l":"Utility","a":"CD","g":"Empath"},
  "Curse of the Wilds": {"b":"D","l":"Debilitation","a":"COTW","g":"Ranger"},
  "Curse of Zachriedek": {"b":"D","l":"Debilitation","a":"COZ","g":"Cleric"},
  "Cyclone": {"b":"B","l":"Berserk","g":"Barbarian"},
  "Damaris' Lullaby": {"b":"D","l":"Debilitation","a":"DALU","g":"Bard"},
  "Dazzle": {"b":"D","l":"Debilitation","a":"dazzle","g":"Moon Mage"},
  "Deadfall": {"b":"D","l":"Debilitation","a":"DF","g":"Ranger"},
  "Death's Embrace": {"b":"R","l":"Roar","g":"Barbarian"},
  "Death's Shriek": {"b":"R","l":"Roar","g":"Barbarian"},
  "Defiance": {"b":"S","l":"Scream","g":"Bard"},
  "Demrris' Resolve": {"b":"D","l":"Debilitation","a":"DMRS","g":"Bard"},
  "Desert's Maelstrom": {"b":"D","l":"Debilitation","a":"DEMA","g":"Bard"},
  "Destiny Cipher": {"b":"U","l":"Utility","a":"DC","g":"Moon Mage"},
  "Devitalize": {"b":"T","l":"Targeted Magic","a":"DEVI","g":"Ranger"},
  "Devolve": {"b":"D","l":"Debilitation","a":"DE","g":"Ranger"},
  "Devour": {"b":"U","l":"Utility","a":"devour","g":"Necromancer"},
  "Dinazen Olkar": {"b":"T","l":"Targeted Magic","a":"DO","g":"Moon Mage"},
  "Dispel": {"b":"U","l":"Utility","a":"DISPEL"},
  "Distant Gaze": {"b":"U","l":"Utility","a":"DG","g":"Moon Mage"},
  "Divine Armor": {"b":"U","l":"Utility","a":"DA","g":"Paladin"},
  "Divine Guidance": {"b":"A","l":"Augmentation","a":"DIG","g":"Paladin"},
  "Divine Radiance": {"b":"U","l":"Utility","a":"DR","g":"Cleric"},
  "Dragon": {"b":"F","l":"Form","g":"Barbarian"},
  "Dragon's Breath": {"b":"T","l":"Targeted Magic","a":"DB","g":"Warrior Mage"},
  "Drought": {"b":"B","l":"Berserk","g":"Barbarian"},
  "Drums of the Snake": {"b":"A","l":"Augmentation","a":"DRUM","g":"Bard"},
  "Eagle": {"b":"F","l":"Form","g":"Barbarian"},
  "Eagle's Cry": {"b":"T","l":"Targeted Magic","a":"EC","g":"Ranger"},
  "Earth Meld": {"b":"A","l":"Augmentation","a":"EM","g":"Ranger"},
  "Earthquake": {"b":"B","l":"Berserk","g":"Barbarian"},
  "Ease Burden": {"b":"A","l":"Augmentation","a":"EASE"},
  "Ebon Blood of the Scorpion": {"b":"X","l":"Metamagic","a":"EBOTS","g":"Necromancer"},
  "Echoes of Aether": {"b":"A","l":"Augmentation","a":"ECHO","g":"Bard"},
  "Eillie's Cry": {"b":"A","l":"Augmentation","a":"ECRY","g":"Bard"},
  "Electric Charge": {"b":"C","l":"Cantrip","a":"C E C","g":"Warrior Mage"},
  "Electrostatic Eddy": {"b":"D","l":"Debilitation","a":"EE","g":"Warrior Mage"},
  "Elementalism": {"b":"X","l":"Metamagic","g":"Warrior Mage"},
  "Elision": {"b":"W","l":"Warding","a":"ELI","g":"Trader"},
  "Embed the Cycle": {"b":"W","l":"Warding","a":"ETC","g":"Ranger"},
  "Embrace of the Vela'Tohr": {"b":"U","l":"Utility","a":"EV","g":"Empath"},
  "Empower Moonblade": {"b":"X","l":"Metamagic","a":"EMMO","g":"Moon Mage"},
  "Emuin's Candlelight": {"b":"A","l":"Augmentation","a":"EMC","g":"Necromancer"},
  "Enrichment": {"b":"A","l":"Augmentation","a":"ENRICH","g":"Trader"},
  "Essence of Yew": {"b":"W","l":"Warding","a":"EY","g":"Ranger"},
  "Ethereal Fissure": {"b":"U","l":"Utility","a":"ETF","g":"Warrior Mage"},
  "Ethereal Shield": {"b":"W","l":"Warding","a":"ES","g":"Warrior Mage"},
  "Everild's Rage": {"b":"R","l":"Roar","g":"Barbarian"},
  "Expansive Infusions": {"b":"X","l":"Metamagic","g":"Warrior Mage"},
  "Eye of Kertigen": {"b":"U","l":"Utility","a":"EYE","g":"Bard"},
  "Eyes of the Blind": {"b":"U","l":"Utility","a":"EOTB","g":"Necromancer"},
  "Eylhaar's Feast": {"b":"U","l":"Utility","a":"EF","g":"Cleric"},
  "Faenella's Grace": {"b":"A","l":"Augmentation","a":"FAE","g":"Bard"},
  "Failure of the Forge": {"b":"W","l":"Warding","a":"FOTF","g":"Bard"},
  "Famine": {"b":"B","l":"Berserk","g":"Barbarian"},
  "Fiery Infusions": {"b":"X","l":"Metamagic","g":"Warrior Mage"},
  "Finesse": {"b":"A","l":"Augmentation","a":"FIN","g":"Trader"},
  "Fire Ball": {"b":"T","l":"Targeted Magic","a":"FB","g":"Warrior Mage"},
  "Fire of Ushnish": {"b":"T","l":"Targeted Magic","a":"FOU","g":"Cleric"},
  "Fire Rain": {"b":"T","l":"Targeted Magic","a":"FR","g":"Warrior Mage"},
  "Fire Shards": {"b":"T","l":"Targeted Magic","a":"FS","g":"Warrior Mage"},
  "Fists of Faenella": {"b":"T","l":"Targeted Magic","a":"FF","g":"Cleric"},
  "Flame Shockwave": {"b":"X","l":"Metamagic","a":"FLS","g":"Warrior Mage"},
  "Flash Point": {"b":"C","l":"Cantrip","a":"C F","g":"Warrior Mage"},
  "Flashflood": {"b":"B","l":"Berserk","g":"Barbarian"},
  "Fluoresce": {"b":"D","l":"Debilitation","a":"fluoresce","g":"Trader"},
  "Flush Poisons": {"b":"U","l":"Utility","a":"FP","g":"Empath"},
  "Focus": {"b":"M","l":"Meditation","g":"Barbarian"},
  "Focus Moonbeam": {"b":"U","l":"Utility","a":"FM","g":"Moon Mage"},
  "Footman's Strike": {"b":"T","l":"Targeted Magic","a":"FST","g":"Paladin"},
  "Forestwalker's Boon": {"b":"W","l":"Warding","a":"FWB","g":"Ranger"},
  "Fortress of Ice": {"b":"U","l":"Utility","a":"FOI","g":"Warrior Mage"},
  "Fountain of Creation": {"b":"U","l":"Utility","a":"FOC","g":"Empath"},
  "Frost Scythe": {"b":"T","l":"Targeted Magic","a":"FRS","g":"Warrior Mage"},
  "Frostbite": {"b":"D","l":"Debilitation","a":"frostbite","g":"Warrior Mage"},
  "Gam Irnan": {"b":"W","l":"Warding","a":"GI","g":"Warrior Mage"},
  "Gar Zeng": {"b":"T","l":"Targeted Magic","a":"GZ","g":"Warrior Mage"},
  "Gauge Flow": {"b":"U","l":"Utility","a":"GAF"},
  "Geyser": {"b":"T","l":"Targeted Magic","a":"geyser","g":"Warrior Mage"},
  "Ghost Shroud": {"b":"W","l":"Warding","a":"GHS","g":"Cleric"},
  "Ghoulflesh": {"b":"W","l":"Warding","a":"ghoulflesh","g":"Necromancer"},
  "Gift of Life": {"b":"A","l":"Augmentation","a":"GOL","g":"Empath"},
  "Glythtide's Gift": {"b":"A","l":"Augmentation","a":"GG","g":"Cleric"},
  "Glythtide's Joy": {"b":"W","l":"Warding","a":"GJ","g":"Bard"},
  "Grizzly Claws": {"b":"D","l":"Debilitation","a":"GRIZ","g":"Ranger"},
  "Grounding Field": {"b":"W","l":"Warding","a":"GF","g":"Warrior Mage"},
  "Guardian Spirit": {"b":"U","l":"Utility","a":"GS","g":"Empath"},
  "Gust of Wind": {"b":"C","l":"Cantrip","a":"C G O W","g":"Warrior Mage"},
  "Halo": {"b":"D","l":"Debilitation","a":"HALO","g":"Cleric"},
  "Halt": {"b":"D","l":"Debilitation","a":"halt","g":"Paladin"},
  "Hand of Tenemlor": {"b":"T","l":"Targeted Magic","a":"HOT","g":"Cleric"},
  "Hands of Justice": {"b":"U","l":"Utility","a":"HOJ","g":"Paladin"},
  "Hands of Lirisa": {"b":"A","l":"Augmentation","a":"HOL","g":"Ranger"},
  "Harawep's Bonds": {"b":"D","l":"Debilitation","a":"HB","g":"Ranger"},
  "Harm Evil": {"b":"T","l":"Targeted Magic","a":"HE","g":"Cleric"},
  "Harm Horde": {"b":"T","l":"Targeted Magic","a":"HH","g":"Cleric"},
  "Harmony": {"b":"A","l":"Augmentation","a":"Harmony","g":"Bard"},
  "Havoc": {"b":"S","l":"Scream","g":"Bard"},
  "Heal": {"b":"U","l":"Utility","a":"heal","g":"Empath"},
  "Heal Scars": {"b":"U","l":"Utility","a":"HS","g":"Empath"},
  "Heal Wounds": {"b":"U","l":"Utility","a":"HW","g":"Empath"},
  "Heart Link": {"b":"U","l":"Utility","a":"HL","g":"Empath"},
  "Heavenly Fires": {"b":"X","l":"Metamagic","a":"HF","g":"Cleric"},
  "Heighten Pain": {"b":"D","l":"Debilitation","a":"HP","g":"Necromancer"},
  "Heitak": {"b":"F","l":"Form","g":"Barbarian"},
  "Heroic Strength": {"b":"A","l":"Augmentation","a":"HES","g":"Paladin"},
  "Hodierna's Lilt": {"b":"U","l":"Utility","a":"HODI","g":"Bard"},
  "Holy Warrior": {"b":"W","l":"Warding","a":"HOW","g":"Paladin"},
  "Horn of the Black Unicorn": {"b":"T","l":"Targeted Magic","a":"HORN","g":"Cleric"},
  "Huldah's Pall": {"b":"D","l":"Debilitation","a":"HULP","g":"Cleric"},
  "Hurricane": {"b":"B","l":"Berserk","g":"Barbarian"},
  "Hydra Hex": {"b":"D","l":"Debilitation","a":"HYH","g":"Cleric"},
  "Hypnotize": {"b":"X","l":"Metamagic","g":"Moon Mage"},
  "Ice Patch": {"b":"D","l":"Debilitation","a":"IP","g":"Warrior Mage"},
  "Icutu Zaharenela": {"b":"T","l":"Targeted Magic","a":"IZ","g":"Empath"},
  "Icy Infusions": {"b":"X","l":"Metamagic","g":"Warrior Mage"},
  "Idon's Theft": {"b":"D","l":"Debilitation","a":"IT","g":"Cleric"},
  "Ignite": {"b":"U","l":"Utility","a":"ignite","g":"Warrior Mage"},
  "Ignition Point": {"b":"X","l":"Metamagic","g":"Warrior Mage"},
  "Imbue": {"b":"U","l":"Utility","a":"IMBUE"},
  "Innocence": {"b":"U","l":"Utility","a":"INNOCENCE","g":"Empath"},
  "Instinct": {"b":"A","l":"Augmentation","a":"INST","g":"Ranger"},
  "Invocation of the Spheres": {"b":"A","l":"Augmentation","a":"IOTS","g":"Moon Mage"},
  "Iridius Rod": {"b":"W","l":"Warding","a":"IR","g":"Trader"},
  "Iron Constitution": {"b":"W","l":"Warding","a":"IC","g":"Empath"},
  "Ivory Mask": {"b":"A","l":"Augmentation","a":"IVM","g":"Necromancer"},
  "Iyqaromos Fire-Lens": {"b":"X","l":"Metamagic","a":"IFL","g":"Moon Mage"},
  "Kuniyo's Strike": {"b":"R","l":"Roar","g":"Barbarian"},
  "Kura-Silma": {"b":"A","l":"Augmentation","a":"KS","g":"Necromancer"},
  "Landslide": {"b":"B","l":"Berserk","g":"Barbarian"},
  "Last Gift of Vithwok IV": {"b":"A","l":"Augmentation","a":"LGV","g":"Trader"},
  "Lay Ward": {"b":"W","l":"Warding","a":"LW"},
  "Lethargy": {"b":"D","l":"Debilitation","a":"LETHARGY","g":"Empath"},
  "Lightning Bolt": {"b":"T","l":"Targeted Magic","a":"LB","g":"Warrior Mage"},
  "Liturgy": {"b":"X","l":"Metamagic","g":"Necromancer"},
  "Locate": {"b":"U","l":"Utility","a":"locate","g":"Moon Mage"},
  "Machinist's Touch": {"b":"A","l":"Augmentation","a":"MT","g":"Moon Mage"},
  "Mage's Lash": {"b":"R","l":"Roar","g":"Barbarian"},
  "Magnetic Ballista": {"b":"U","l":"Utility","a":"MAB","g":"Warrior Mage"},
  "Malediction": {"b":"D","l":"Debilitation","a":"malediction","g":"Cleric"},
  "Mana Torment": {"b":"R","l":"Roar","g":"Barbarian"},
  "Manifest Force": {"b":"W","l":"Warding","a":"MAF"},
  "Mantle of Flame": {"b":"A","l":"Augmentation","a":"MOF","g":"Warrior Mage"},
  "Mark of Arhat": {"b":"D","l":"Debilitation","a":"MOA","g":"Warrior Mage"},
  "Marshal Order": {"b":"A","l":"Augmentation","a":"MO","g":"Paladin"},
  "Mask of the Moons": {"b":"W","l":"Warding","a":"MOM","g":"Trader"},
  "Mass Rejuvenation": {"b":"U","l":"Utility","a":"MRE","g":"Cleric"},
  "Membrach's Greed": {"b":"A","l":"Augmentation","a":"MEG","g":"Trader"},
  "Memory of Nature": {"b":"U","l":"Utility","a":"MON","g":"Ranger"},
  "Mental Blast": {"b":"D","l":"Debilitation","a":"MB","g":"Moon Mage"},
  "Mental Focus": {"b":"A","l":"Augmentation","a":"MEF","g":"Empath"},
  "Meraud's Cry": {"b":"D","l":"Debilitation","a":"MC","g":"Cleric"},
  "Mind Shout": {"b":"D","l":"Debilitation","a":"MS","g":"Moon Mage"},
  "Misdirection": {"b":"A","l":"Augmentation","a":"MIS","g":"Bard"},
  "Monkey": {"b":"F","l":"Form","g":"Barbarian"},
  "Moonblade": {"b":"U","l":"Utility","a":"moonblade","g":"Moon Mage"},
  "Moongate": {"b":"U","l":"Utility","a":"MG","g":"Moon Mage"},
  "Murrula's Flames": {"b":"U","l":"Utility","a":"MF","g":"Cleric"},
  "Naming of Tears": {"b":"W","l":"Warding","a":"NAME","g":"Bard"},
  "Necrotic Reconstruction": {"b":"U","l":"Utility","a":"NR","g":"Necromancer"},
  "Nexus": {"b":"U","l":"Utility","a":"NEXUS","g":"Bard"},
  "Nissa's Binding": {"b":"D","l":"Debilitation","a":"NB","g":"Empath"},
  "Nonchalance": {"b":"W","l":"Warding","a":"NON","g":"Trader"},
  "Noumena": {"b":"U","l":"Utility","a":"NOU","g":"Trader"},
  "Oath of the Firstborn": {"b":"A","l":"Augmentation","a":"OATH","g":"Ranger"},
  "Obfuscation": {"b":"A","l":"Augmentation","a":"obfuscation","g":"Necromancer"},
  "Osrel Meraud": {"b":"U","l":"Utility","a":"OM","g":"Cleric"},
  "Ouroboral Thoughts": {"b":"W","l":"Warding","a":"OT","g":"Trader"},
  "Owl": {"b":"F","l":"Form","g":"Barbarian"},
  "Paeldryth's Wrath": {"b":"T","l":"Targeted Magic","a":"PW","g":"Warrior Mage"},
  "Panther": {"b":"F","l":"Form","g":"Barbarian"},
  "Paralysis": {"b":"T","l":"Targeted Magic","a":"PARALYSIS","g":"Empath"},
  "Partial Displacement": {"b":"T","l":"Targeted Magic","a":"PD","g":"Moon Mage"},
  "Pattern Hues": {"b":"C","l":"Cantrip","a":"C P H","g":"Warrior Mage"},
  "Perseverance of Peri'el": {"b":"W","l":"Warding","a":"POP","g":"Empath"},
  "Persistence of Mana": {"b":"A","l":"Augmentation","a":"POM","g":"Cleric"},
  "Petrifying Visions": {"b":"D","l":"Debilitation","a":"PV","g":"Necromancer"},
  "Phelim's Sanction": {"b":"D","l":"Debilitation","a":"PS","g":"Cleric"},
  "Philosopher's Preservation": {"b":"A","l":"Augmentation","a":"PHP","g":"Necromancer"},
  "Phoenix's Pyre": {"b":"T","l":"Targeted Magic","a":"PYRE","g":"Bard"},
  "Piercing Gaze": {"b":"U","l":"Utility","a":"PG","g":"Moon Mage"},
  "Piranha": {"b":"F","l":"Form","g":"Barbarian"},
  "Plague of Scavengers": {"b":"X","l":"Metamagic","a":"PLS","g":"Ranger"},
  "Platinum Hands of Kertigen": {"b":"A","l":"Augmentation","a":"PHK","g":"Trader"},
  "Prosperity Everlasting": {"b":"X","l":"Metamagic","a":"PREV","g":"Trader"},
  "Prosperity in Darkness": {"b":"X","l":"Metamagic","a":"PRDA","g":"Trader"},
  "Protection from Evil": {"b":"W","l":"Warding","a":"PFE","g":"Cleric"},
  "Psychic Shield": {"b":"W","l":"Warding","a":"PSY","g":"Moon Mage"},
  "Python": {"b":"F","l":"Form","g":"Barbarian"},
  "Quick Infusions": {"b":"X","l":"Metamagic","g":"Warrior Mage"},
  "Quicken the Earth": {"b":"U","l":"Utility","a":"QE","g":"Necromancer"},
  "Rage of the Clans": {"b":"A","l":"Augmentation","a":"RAGE","g":"Bard"},
  "Raincloud": {"b":"C","l":"Cantrip","a":"C Raincloud","g":"Warrior Mage"},
  "Raise Power": {"b":"U","l":"Utility","a":"RP","g":"Empath"},
  "Read the Ripples": {"b":"U","l":"Utility","a":"RtR","g":"Moon Mage"},
  "Rebuke": {"b":"T","l":"Targeted Magic","a":"REB","g":"Paladin"},
  "Redeemer's Pride": {"b":"W","l":"Warding","a":"REPR","g":"Bard"},
  "Refractive Field": {"b":"U","l":"Utility","a":"RF","g":"Moon Mage"},
  "Refresh": {"b":"A","l":"Augmentation","a":"Refresh","g":"Empath"},
  "Regalia": {"b":"U","l":"Utility","a":"REGAL","g":"Trader"},
  "Regenerate": {"b":"U","l":"Utility","a":"regenerate","g":"Empath"},
  "Reinforce Stone": {"b":"C","l":"Cantrip","a":"C R S","g":"Warrior Mage"},
  "Reinforced Infusions": {"b":"X","l":"Metamagic","g":"Warrior Mage"},
  "Rejuvenation": {"b":"U","l":"Utility","a":"REJUV","g":"Cleric"},
  "Rend": {"b":"U","l":"Utility","a":"rend","g":"Moon Mage"},
  "Researcher's Insight": {"b":"A","l":"Augmentation","a":"REI","g":"Necromancer"},
  "Resonance": {"b":"U","l":"Utility","a":"RESONANCE","g":"Bard"},
  "Resumption": {"b":"X","l":"Metamagic","a":"RESUM","g":"Trader"},
  "Resurrection": {"b":"U","l":"Utility","a":"REZZ","g":"Cleric"},
  "Revelation": {"b":"U","l":"Utility","a":"revelation","g":"Cleric"},
  "Reverse Putrefaction": {"b":"A","l":"Augmentation","a":"RPU","g":"Necromancer"},
  "Riftal Summons": {"b":"U","l":"Utility","a":"RS","g":"Moon Mage"},
  "Righteous Wrath": {"b":"A","l":"Augmentation","a":"RW","g":"Paladin"},
  "Rimefang": {"b":"T","l":"Targeted Magic","a":"RIM","g":"Warrior Mage"},
  "Ring of Spears": {"b":"T","l":"Targeted Magic","a":"ROS","g":"Warrior Mage"},
  "Ripplegate Theory": {"b":"X","l":"Metamagic","a":"RT","g":"Moon Mage"},
  "Rising Mists": {"b":"U","l":"Utility","a":"RM","g":"Warrior Mage"},
  "Rite of Contrition": {"b":"U","l":"Utility","a":"ROC","g":"Necromancer"},
  "Rite of Forbearance": {"b":"U","l":"Utility","a":"RoF","g":"Necromancer"},
  "Rite of Grace": {"b":"U","l":"Utility","a":"ROG","g":"Necromancer"},
  "River in the Sky": {"b":"W","l":"Warding","a":"RITS","g":"Ranger"},
  "Rutilor's Edge": {"b":"U","l":"Utility","a":"RUE","g":"Paladin"},
  "Saesordian Compass": {"b":"A","l":"Augmentation","a":"SCO","g":"Moon Mage"},
  "Sanctify Pattern": {"b":"A","l":"Augmentation","a":"SAP","g":"Cleric"},
  "Sanctuary": {"b":"U","l":"Utility","a":"SANCTUARY","g":"Bard"},
  "Sanyu Lyba": {"b":"W","l":"Warding","a":"SL","g":"Cleric"},
  "Screech of Madness": {"b":"R","l":"Roar","g":"Barbarian"},
  "Seal Cambrinth": {"b":"U","l":"Utility","a":"SEC"},
  "See the Wind": {"b":"A","l":"Augmentation","a":"STW","g":"Ranger"},
  "Seek": {"b":"M","l":"Meditation","g":"Barbarian"},
  "Seer's Sense": {"b":"A","l":"Augmentation","a":"SEER","g":"Moon Mage"},
  "Senses of the Tiger": {"b":"A","l":"Augmentation","a":"SOTT","g":"Ranger"},
  "Sentinel's Resolve": {"b":"A","l":"Augmentation","a":"SR","g":"Paladin"},
  "Serenity": {"b":"M","l":"Meditation","g":"Barbarian"},
  "Serpent's Hiss": {"b":"R","l":"Roar","g":"Barbarian"},
  "Sever Thread": {"b":"D","l":"Debilitation","a":"SET","g":"Moon Mage"},
  "Shadewatch Mirror": {"b":"U","l":"Utility","a":"SHM","g":"Moon Mage"},
  "Shadow Servant": {"b":"U","l":"Utility","a":"SS","g":"Moon Mage"},
  "Shadow Web": {"b":"D","l":"Debilitation","a":"SHW","g":"Moon Mage"},
  "Shadowling": {"b":"U","l":"Utility","a":"shadowling","g":"Moon Mage"},
  "Shadows": {"b":"A","l":"Augmentation","a":"shadows","g":"Moon Mage"},
  "Shape Moonblade": {"b":"X","l":"Metamagic","a":"SHMO","g":"Moon Mage"},
  "Shatter": {"b":"D","l":"Debilitation","a":"shatter","g":"Paladin"},
  "Shear": {"b":"W","l":"Warding","a":"shear","g":"Moon Mage"},
  "Shield of Light": {"b":"A","l":"Augmentation","a":"SOL","g":"Cleric"},
  "Shift Moonbeam": {"b":"U","l":"Utility","a":"SM","g":"Moon Mage"},
  "Shocking Infusions": {"b":"X","l":"Metamagic","g":"Warrior Mage"},
  "Shockwave": {"b":"T","l":"Targeted Magic","a":"shockwave","g":"Warrior Mage"},
  "Sidasas Sedra": {"b":"X","l":"Metamagic","g":"Paladin"},
  "Sidhlot's Flaying": {"b":"T","l":"Targeted Magic","a":"SIF","g":"Necromancer"},
  "Siphon Vitality": {"b":"T","l":"Targeted Magic","a":"SV","g":"Necromancer"},
  "Skein of Shadows": {"b":"A","l":"Augmentation","a":"SKS","g":"Ranger"},
  "Slash the Shadows": {"b":"R","l":"Roar","g":"Barbarian"},
  "Sleep": {"b":"D","l":"Debilitation","a":"sleep","g":"Moon Mage"},
  "Smite Horde": {"b":"T","l":"Targeted Magic","a":"SMH","g":"Paladin"},
  "Solace": {"b":"W","l":"Warding","a":"SOLACE","g":"Necromancer"},
  "Soldier's Prayer": {"b":"W","l":"Warding","a":"SP","g":"Paladin"},
  "Sorrow": {"b":"T","l":"Targeted Magic","a":"sorrow","g":"Moon Mage"},
  "Soul Ablaze": {"b":"A","l":"Augmentation","a":"SOUL","g":"Bard"},
  "Soul Attrition": {"b":"T","l":"Targeted Magic","a":"SA","g":"Cleric"},
  "Soul Bonding": {"b":"D","l":"Debilitation","a":"SB","g":"Cleric"},
  "Soul Shield": {"b":"W","l":"Warding","a":"SOS","g":"Cleric"},
  "Soul Sickness": {"b":"D","l":"Debilitation","a":"SICK","g":"Cleric"},
  "Sovereign Destiny": {"b":"D","l":"Debilitation","a":"SOD","g":"Moon Mage"},
  "Spite of Dergati": {"b":"D","l":"Debilitation","a":"SPIT","g":"Cleric"},
  "Spiteful Rebirth": {"b":"X","l":"Metamagic","a":"SRE","g":"Necromancer"},
  "Stampede": {"b":"T","l":"Targeted Magic","a":"STAMPEDE","g":"Ranger"},
  "Starcrash": {"b":"T","l":"Targeted Magic","a":"starcrash","g":"Trader"},
  "Starforged Regalia": {"b":"X","l":"Metamagic","a":"SFR","g":"Trader"},
  "Starlight Sphere": {"b":"T","l":"Targeted Magic","a":"SLS","g":"Moon Mage"},
  "Starry Waters": {"b":"A","l":"Augmentation","a":"STAW","g":"Cleric"},
  "Staunch": {"b":"M","l":"Meditation","g":"Barbarian"},
  "Stellar Collector": {"b":"U","l":"Utility","a":"STC","g":"Trader"},
  "Steps of Vuan": {"b":"U","l":"Utility","a":"SOV","g":"Moon Mage"},
  "Stone Seat": {"b":"C","l":"Cantrip","a":"C S S","g":"Warrior Mage"},
  "Stone Strike": {"b":"T","l":"Targeted Magic","a":"STS","g":"Warrior Mage"},
  "Strange Arrow": {"b":"T","l":"Targeted Magic","a":"STRA"},
  "Stun Foe": {"b":"D","l":"Debilitation","a":"SF","g":"Paladin"},
  "Substratum": {"b":"A","l":"Augmentation","a":"substratum","g":"Warrior Mage"},
  "Sure Footing": {"b":"A","l":"Augmentation","a":"SUF","g":"Warrior Mage"},
  "Swan": {"b":"F","l":"Form","g":"Barbarian"},
  "Swarm": {"b":"D","l":"Debilitation","a":"SWARM","g":"Ranger"},
  "Swirling Winds": {"b":"A","l":"Augmentation","a":"SW","g":"Warrior Mage"},
  "Syamelyo Kuniyo": {"b":"A","l":"Augmentation","a":"SK","g":"Ranger"},
  "Tailwind": {"b":"A","l":"Augmentation","a":"TW","g":"Warrior Mage"},
  "Tamsine's Kiss": {"b":"W","l":"Warding","a":"TK","g":"Paladin"},
  "Tangled Fate": {"b":"D","l":"Debilitation","a":"TF","g":"Moon Mage"},
  "Telekinetic Shield": {"b":"W","l":"Warding","a":"TKSH","g":"Moon Mage"},
  "Telekinetic Storm": {"b":"T","l":"Targeted Magic","a":"TKS","g":"Moon Mage"},
  "Telekinetic Throw": {"b":"T","l":"Targeted Magic","a":"TKT","g":"Moon Mage"},
  "Teleport": {"b":"U","l":"Utility","a":"TELEPORT","g":"Moon Mage"},
  "Tenacity": {"b":"M","l":"Meditation","g":"Barbarian"},
  "Tenebrous Sense": {"b":"A","l":"Augmentation","a":"TS","g":"Moon Mage"},
  "Tezirah's Veil": {"b":"A","l":"Augmentation","a":"TV","g":"Moon Mage"},
  "Thoughtcast": {"b":"U","l":"Utility","a":"TH","g":"Moon Mage"},
  "Thunderclap": {"b":"D","l":"Debilitation","a":"TC","g":"Warrior Mage"},
  "Time of the Red Spiral": {"b":"X","l":"Metamagic","a":"TOTRS","g":"Cleric"},
  "Tingle": {"b":"D","l":"Debilitation","a":"TI","g":"Warrior Mage"},
  "Toad": {"b":"F","l":"Form","g":"Barbarian"},
  "Tornado": {"b":"B","l":"Berserk","g":"Barbarian"},
  "Trabe Chalice": {"b":"W","l":"Warding","a":"TRC","g":"Trader"},
  "Tranquility": {"b":"W","l":"Warding","a":"TRANQUILITY","g":"Empath"},
  "Tremor": {"b":"D","l":"Debilitation","a":"tremor","g":"Warrior Mage"},
  "Truffenyi's Rally": {"b":"A","l":"Augmentation","a":"TR","g":"Paladin"},
  "Tsunami": {"b":"B","l":"Berserk","g":"Barbarian"},
  "Turmar Illumination": {"b":"A","l":"Augmentation","a":"TURI","g":"Trader"},
  "Turtle": {"b":"F","l":"Form","g":"Barbarian"},
  "Uncurse": {"b":"U","l":"Utility","a":"UNCURSE","g":"Cleric"},
  "Universal Solvent": {"b":"T","l":"Targeted Magic","a":"USOL","g":"Necromancer"},
  "Unleash": {"b":"U","l":"Utility","a":"unleash","g":"Moon Mage"},
  "Unyielding": {"b":"M","l":"Meditation","g":"Barbarian"},
  "Veil of Ice": {"b":"W","l":"Warding","a":"VOI","g":"Warrior Mage"},
  "Vertigo": {"b":"D","l":"Debilitation","a":"vertigo","g":"Warrior Mage"},
  "Vessel of Salvation": {"b":"U","l":"Utility","a":"VOS","g":"Paladin"},
  "Veteran Insight": {"b":"X","l":"Metamagic","a":"VETERAN","g":"Paladin"},
  "Vigil": {"b":"U","l":"Utility","a":"VIGIL","g":"Cleric"},
  "Vigor": {"b":"A","l":"Augmentation","a":"VIGOR","g":"Empath"},
  "Visage": {"b":"W","l":"Warding","a":"VISAGE","g":"Cleric"},
  "Viscous Solution": {"b":"D","l":"Debilitation","a":"VS","g":"Necromancer"},
  "Visions of Darkness": {"b":"D","l":"Debilitation","a":"VOD","g":"Necromancer"},
  "Vitality Healing": {"b":"U","l":"Utility","a":"VH","g":"Empath"},
  "Vivisection": {"b":"T","l":"Targeted Magic","a":"vivisection","g":"Necromancer"},
  "Volcano": {"b":"B","l":"Berserk","g":"Barbarian"},
  "Wail of Torment": {"b":"R","l":"Roar","g":"Barbarian"},
  "Ward Break": {"b":"D","l":"Debilitation","a":"WB","g":"Warrior Mage"},
  "Water Globe": {"b":"C","l":"Cantrip","a":"C Water Globe","g":"Warrior Mage"},
  "Whispers of the Muse": {"b":"A","l":"Augmentation","a":"WOTM","g":"Bard"},
  "Whole Displacement": {"b":"W","l":"Warding","a":"WD","g":"Moon Mage"},
  "Wildfire": {"b":"B","l":"Berserk","g":"Barbarian"},
  "Will O Wisp": {"b":"C","l":"Cantrip","a":"C W O W","g":"Warrior Mage"},
  "Will of Winter": {"b":"A","l":"Augmentation","a":"WILL","g":"Bard"},
  "Wisdom of the Pack": {"b":"A","l":"Augmentation","a":"WOTP","g":"Ranger"},
  "Wolf Scent": {"b":"A","l":"Augmentation","a":"WS","g":"Ranger"},
  "Wolverine": {"b":"F","l":"Form","g":"Barbarian"},
  "Words of the Wind": {"b":"A","l":"Augmentation","a":"WORD","g":"Bard"},
  "Worm's Mist": {"b":"W","l":"Warding","a":"WORM","g":"Necromancer"},
  "Y'ntrel Sechra": {"b":"A","l":"Augmentation","a":"YS","g":"Warrior Mage"},
  "Zephyr": {"b":"U","l":"Utility","a":"zephyr","g":"Warrior Mage"},
}

// Case-insensitive fallback index. The names match verbatim in every capture we
// have, so this only ever covers a casing drift we have not seen.
const BY_LOWER: Record<string, SpellRef> = {}
for (const k in SPELL_DATA) BY_LOWER[k.toLowerCase()] = SPELL_DATA[k]

export function lookupSpell(name: string): SpellRef | undefined {
  return SPELL_DATA[name] ?? BY_LOWER[name.toLowerCase()]
}
